logging:
  logLevel: info
http:
  port: 4800
rmr:
  port: 4801
  maxMsgSize: 65536
  readyIntervalSec: 1
rnib:
  maxRnibConnectionAttempts: 3
  rnibRetryIntervalMs: 10
resourceStatusParams:
  enableResourceStatus: true
  partialSuccessAllowed: true
  prbPeriodic: true
  tnlLoadIndPeriodic: true
  hwLoadIndPeriodic: true
  absStatusPeriodic: true
  rsrpMeasurementPeriodic: true
  csiPeriodic: true
  periodicityMs: 1000
  periodicityRsrpMeasurementMs: 480
  periodicityCsiMs: 20
